version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - '1111:3000'
  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - '2222:3000'

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - '3333:3000'
